#!/bin/sh -e

# Remember the current working directory
CURRENT_DIR="$PWD"

# Change to Workcraft home directory and put it into the WORKCRAFT_HOME variable
cd "$(dirname "$0")"
WORKCRAFT_HOME="$PWD"

# Set the JVM executable in JAVA_BIN variable (if not defined yet)
if [ -z "$JAVA_BIN" ]; then
    if [ -z "$JAVA_HOME" ]; then
        JAVA_BIN=java
    else
        if [ -e "$JAVA_HOME/bin/java" ]; then
            JAVA_BIN="$JAVA_HOME/bin/java"
        else
            JAVA_BIN="$JAVA_HOME/java"
        fi
    fi
fi

# Check presence of Java binary
if [ -z $(command -v "$JAVA_BIN") ]; then
    echo "Cannot find Java binary $JAVA_BIN"
    exit
fi

# Check correctness of Java version
JAVA_VERSION=$("$JAVA_BIN" -fullversion 2>&1 | sed -n ';s/.* version "\([0-9]\+\)\(\.[0-9]\+\)\?.*".*/\1\2/p;')
if [ "$JAVA_VERSION" != "1.8" ]; then
    echo "Java 1.8 is required, but version $JAVA_VERSION is found."
    exit
fi

export CLASSPATH="$WORKCRAFT_HOME/bin/*"

"$JAVA_BIN" org.workcraft.Console -dir:"$CURRENT_DIR" "$@"
