#!/bin/sh -e

# Remember the current working directory
CURRENT_DIR="$PWD"

# Change to Workcraft home directory and put it into the WORKCRAFT_HOME variable
cd "$(dirname "$(readlink -f $0)")"
WORKCRAFT_HOME="$PWD"

# Use bundled JRE as the first priority (if present and not overridden)
if [ -z "$WORKCRAFT_USE_NATIVE_JAVA" ]; then
    if [ -e "$WORKCRAFT_HOME/jre/bin/java" ]; then
        JAVA_BIN="$WORKCRAFT_HOME/jre/bin/java"
    fi
fi

# Set the JVM executable in JAVA_BIN variable (if not defined yet)
if [ -z "$JAVA_BIN" ]; then
    if [ -z "$JAVA_HOME" ]; then
        JAVA_BIN=java
    else
        if [ -e "$JAVA_HOME/bin/java" ]; then
            JAVA_BIN="$JAVA_HOME/bin/java"
        else
            JAVA_BIN="$JAVA_HOME/java"
        fi
    fi
fi

# Check presence of Java binary
if [ -z $(command -v "$JAVA_BIN") ]; then
    echo "Cannot find Java binary $JAVA_BIN"
    exit
fi

export CLASSPATH="$WORKCRAFT_HOME/bin/*"

"$JAVA_BIN" org.workcraft.Console -dir:"$CURRENT_DIR" "$@"
